services:
  - type: web
    name: sciencebuddy
    env: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app -c gunicorn_config.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
